branch-defaults:
  master:
    environment: sleepingPillCore-prod
environment-defaults:
  sleepingPillCore-prod:
    branch: null
    repository: null
global:
  application_name: sleepingPillCore
  default_platform: java-8
  default_ec2_keyname: javabin
  default_platform: 64bit Amazon Linux 2017.03 v2.5.4 running Java 8
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip